(** * Phase 6b: The JTS forcing translation, mechanized (propositional fragment)

    Phase 6 asserts — in prose — that [iProp FS] of Phase 4 is
    "literally the propositional fragment of the Jaber–Tabareau–Sozeau
    forcing translation, instantiated at the forcing structure [FS]".
    This file replaces that assertion with a theorem.

    We deep-embed a propositional object language [form] (atoms, ⊤, ⊥,
    ∧, ∨, →, and the later modality ▷), and define the forcing
    translation [jts] exactly as JTS (and, before them, the
    presheaf/Kripke–Joyal semantics) prescribe, as a standalone
    [Fixpoint] on the syntax that never mentions [iProp]:

      [jts ⊤ p        := True]
      [jts ⊥ p        := False]
      [jts (φ ∧ ψ) p  := jts φ p /\ jts ψ p]
      [jts (φ ∨ ψ) p  := jts φ p \/ jts ψ p]
      [jts (φ → ψ) p  := ∀ q ≼ p, jts φ q -> jts ψ q]
      [jts (▷ φ) p    := ∀ q ≺ p, jts φ q]

    Three theorems then make the Phase 6 claim precise:

    - [jts_mono]:      the translation of every formula is downward
                       closed — the translated propositions are
                       presheaves on the conditions, i.e. they *land
                       in* [iProp FS] ([jtsProp]).
    - [jts_is_interp]: the translation *coincides pointwise* with the
                       [iProp]-semantics [interp] that reads the same
                       syntax through Phase 4's connectives.  This is
                       the factorization "syntactic forcing translation
                       = step-indexed semantics", at every formula and
                       every condition, over an arbitrary
                       [ForcingStructure].
    - [jts_Lob]:       Löb's rule holds *of the translated formulas*:
                       if [jts (▷φ → φ)] is forced at [p], so is
                       [jts φ].  Via [jts_is_interp] this is Phase 4's
                       [iLob], transported to the syntax.  This is the
                       step-indexed-specific content that well-founded
                       forcing adds to the bare JTS translation
                       (cf. [embed_later_distinct] in Phase 6, and the
                       necessity result of Phase 5).

    What is (still) *not* mechanized: the term-level translation of
    full CIC (universes, dependent products, the definitional side of
    the 2016 paper).  The claim this file cashes out is exactly the
    propositional one made in Phase 6 and in the paper. *)

From Coq Require Import Arith Lia Setoid.
From ForcingHoare Require Import Phase4_Abstract.

Section JTS.
  Variable FS : ForcingStructure.

  (** Atomic propositions: an arbitrary type of atoms, interpreted by
      a monotone (downward-closed) valuation on conditions.  Atoms are
      the imported "already-forced" material; everything else is
      generated by the translation. *)
  Variable A : Type.
  Variable rho : A -> fs_cond FS -> Prop.
  Hypothesis rho_mono :
    forall a p q, fs_le FS q p -> rho a p -> rho a q.

  Local Notation cond := (fs_cond FS).
  Local Notation "q ≼ p" := (fs_le FS q p) (at level 70).
  Local Notation "q ≺ p" := (fs_lt FS q p) (at level 70).

  (** ** The object syntax *)

  Inductive form : Type :=
  | FAtom  (a : A)
  | FTrue
  | FFalse
  | FAnd   (f g : form)
  | FOr    (f g : form)
  | FImpl  (f g : form)
  | FLater (f : form).

  (** ** The forcing translation, as JTS write it

      A plain [Fixpoint] into [cond -> Prop].  Note it does not
      mention [iProp]: this is the *syntactic* translation. *)

  Fixpoint jts (f : form) (p : cond) : Prop :=
    match f with
    | FAtom a    => rho a p
    | FTrue      => True
    | FFalse     => False
    | FAnd g h   => jts g p /\ jts h p
    | FOr g h    => jts g p \/ jts h p
    | FImpl g h  => forall q, q ≼ p -> jts g q -> jts h q
    | FLater g   => forall q, q ≺ p -> jts g q
    end.

  (** ** The translation lands in presheaves

      Downward closure, by induction on the formula.  This is the
      presheaf condition: each translated formula is a monotone
      predicate on conditions — an inhabitant of [iProp FS]. *)

  Lemma jts_mono (f : form) :
    forall p q, q ≼ p -> jts f p -> jts f q.
  Proof.
    induction f; simpl; intros p q Hqp H.
    - (* atom *) eapply rho_mono; eauto.
    - (* ⊤ *) exact I.
    - (* ⊥ *) exact H.
    - (* ∧ *) destruct H as [H1 H2]. split; [eapply IHf1|eapply IHf2]; eauto.
    - (* ∨ *) destruct H as [H1|H2]; [left; eapply IHf1|right; eapply IHf2]; eauto.
    - (* → *) intros r Hrq Hg. apply H; [|exact Hg].
      eapply (fs_le_trans FS); eauto.
    - (* ▷ *) intros r Hrq. apply H.
      eapply (fs_lt_le_lt FS); eauto.
  Qed.

  (** The translated formula, packaged as a step-indexed proposition. *)
  Definition jtsProp (f : form) : iProp FS :=
    MkProp FS (jts f) (jts_mono f).

  (** ** The iProp semantics of the same syntax

      Read the syntax through Phase 4's semantic connectives instead.
      Atoms are interpreted by the same valuation, packaged. *)

  Definition iatom (a : A) : iProp FS :=
    MkProp FS (rho a) (rho_mono a).

  Fixpoint interp (f : form) : iProp FS :=
    match f with
    | FAtom a    => iatom a
    | FTrue      => iTrue FS
    | FFalse     => iFalse FS
    | FAnd g h   => iAnd FS (interp g) (interp h)
    | FOr g h    => iOr FS (interp g) (interp h)
    | FImpl g h  => iImpl FS (interp g) (interp h)
    | FLater g   => iLater FS (interp g)
    end.

  (** ** The factorization theorem

      The syntactic forcing translation and the step-indexed semantics
      agree at every formula and every condition.  This is the
      machine-checked form of "[iProp FS] is the propositional
      fragment of the JTS translation at [FS]": the two sides are
      defined independently — one by recursion into raw [Prop]s, one
      through the [iProp] connectives — and coincide. *)

  Theorem jts_is_interp :
    forall (f : form) (p : cond), jts f p <-> ihold FS (interp f) p.
  Proof.
    induction f; simpl; intros p.
    - (* atom *) tauto.
    - (* ⊤ *) tauto.
    - (* ⊥ *) tauto.
    - (* ∧ *) rewrite (IHf1 p), (IHf2 p). tauto.
    - (* ∨ *) rewrite (IHf1 p), (IHf2 p). tauto.
    - (* → *) split.
      + intros H q Hq Hg. apply IHf2, H, IHf1; assumption.
      + intros H q Hq Hg. apply IHf2, H; [assumption|]. apply IHf1; assumption.
    - (* ▷ *) split.
      + intros H q Hq. apply IHf, H, Hq.
      + intros H q Hq. apply IHf, H, Hq.
  Qed.

  (** Both directions, packaged as entailments between the translated
      proposition and its semantic reading. *)

  Corollary jtsProp_entails_interp (f : form) :
    ientails FS (jtsProp f) (interp f).
  Proof. intros p H. apply jts_is_interp, H. Qed.

  Corollary interp_entails_jtsProp (f : form) :
    ientails FS (interp f) (jtsProp f).
  Proof. intros p H. apply jts_is_interp, H. Qed.

  (** ** Löb's rule, transported to the translated syntax

      The step-indexed-specific dividend: because the forcing notion
      is well-founded, the *translated formulas* satisfy Löb's rule.
      This is the syntax-level face of Phase 4's [iLob]; nothing in
      the bare (non-well-founded) translation provides it, and Phase 5
      shows it fails without well-foundedness. *)

  Theorem jts_Lob (f : form) (p : cond) :
    jts (FImpl (FLater f) f) p -> jts f p.
  Proof.
    intros H.
    apply jts_is_interp.
    apply (iLob FS (interp f)).
    (* [jts (▷f → f) p] is, by the factorization, exactly
       [p ⊩ (▷ interp f → interp f)]. *)
    intros q Hq Hlater.
    apply jts_is_interp.
    apply (H q Hq).
    intros r Hr.
    apply jts_is_interp.
    apply (Hlater r Hr).
  Qed.

End JTS.

(** ** Instantiation at ω

    The concrete step-indexing of Phases 1–3 is the special case
    [FS := nat_FS].  The factorization theorem specializes with no
    further proof — the translation clauses at [nat_FS] are the
    familiar step-indexed readings ([→] quantifies over smaller
    indices, [▷] over strictly smaller ones). *)

Definition jts_nat := jts nat_FS.

Corollary jts_is_interp_nat :
  forall (A : Type) (rho : A -> nat -> Prop)
         (rho_mono : forall a p q, q <= p -> rho a p -> rho a q)
         (f : form A) (n : nat),
    jts nat_FS A rho f n <-> ihold nat_FS (interp nat_FS A rho rho_mono f) n.
Proof. intros. apply jts_is_interp. Qed.

Corollary jts_Lob_nat :
  forall (A : Type) (rho : A -> nat -> Prop)
         (rho_mono : forall a p q, q <= p -> rho a p -> rho a q)
         (f : form A) (n : nat),
    jts nat_FS A rho (FImpl A (FLater A f) f) n -> jts nat_FS A rho f n.
Proof. intros A rho rho_mono f n. apply (jts_Lob nat_FS A rho rho_mono). Qed.
