/-
# Four categorical readings of the calculus

* **Orthogonality.** Linear negation exchanges the calculus of certain states and the local
  calculus (`orth_recipe`, `orth_loc`). The pair `(recipe A, recipe A^⊥)` is a tight orthogonal
  pair iff there is no gap at `A` and at `A^⊥` (`tight_iff`), and at the core it is not
  (`not_tight_core`).
* **Simplices.** On a finite frame the weights of a mixture of point valuations are unique
  (`mix_deltaPoint_inj`). At `Bool ⊸ Bool` two disjoint mixtures of deterministic programs have
  the same behaviour (`lin_not_simplex`). For a presentation whose certain states respect a
  binary meet and a top event, the representing measure of the barycenter theorem is unique on
  the σ-algebra generated by the events (`trim_eq_of_meet`).
* **Limits.** The closed calculus on arbitrarily many events is the limit of the calculi on
  finite windows (`closedCalcEquivLimit`).
-/
import ConstructiveProb.LocalCalculus
import ConstructiveProb.Barycenter
import ConstructiveProb.SumIrreducible

open scoped ENNReal
open MeasureTheory

/-! ### Orthogonality -/

namespace ConstructiveProb.Linear

open ConstructiveProb.PCS (orth)
open Fm

/-- **Negation sends the calculus to the local calculus of the dual.** -/
theorem orth_recipe (A : Fm) : orth (recipe A) = loc (Fm.neg A) := by
  rw [loc_eq, recipe_negneg]

/-- **Negation sends the local calculus to the calculus of the dual.** -/
theorem orth_loc (A : Fm) : orth (loc A) = recipe (Fm.neg A) := by
  rw [loc_eq, recipe_orth_orth]

/-- The orthogonal of the calculus is the calculus of the dual iff neither `A` nor `A^⊥` has a
gap. -/
theorem orth_recipe_eq_iff (A : Fm) :
    orth (recipe A) = recipe (Fm.neg A) ↔ recipe A = P A ∧ recipe (Fm.neg A) = P (Fm.neg A) := by
  rw [orth_recipe]
  have h1 := recipe_sub_P_sub_loc (Fm.neg A)
  have h2 := P_eq_loc_iff (Fm.neg A)
  rw [recipe_negneg, P_negneg] at h2
  constructor
  · intro h
    have hle : loc (Fm.neg A) ⊆ P (Fm.neg A) := by rw [h]; exact h1.1
    refine ⟨h2.1 (le_antisymm h1.2 hle), le_antisymm h1.1 ?_⟩
    rw [← h]; exact h1.2
  · rintro ⟨hA, hnA⟩
    rw [← h2.2 hA, hnA]

/-- **Tightness.** The calculi at `A` and at `A^⊥` are each other's orthogonals iff there is no
gap at either. -/
theorem tight_iff (A : Fm) :
    (orth (recipe A) = recipe (Fm.neg A) ∧ orth (recipe (Fm.neg A)) = recipe A) ↔
      (recipe A = P A ∧ recipe (Fm.neg A) = P (Fm.neg A)) := by
  have h := orth_recipe_eq_iff (Fm.neg A)
  rw [recipe_negneg, P_negneg] at h
  constructor
  · exact fun ⟨h0, _⟩ => (orth_recipe_eq_iff A).1 h0
  · intro hgap
    exact ⟨(orth_recipe_eq_iff A).2 hgap, h.2 ⟨hgap.2, hgap.1⟩⟩

/-- **Tightness is the equality of the calculus and the local calculus.** -/
theorem tight_iff_recipe_eq_loc (A : Fm) :
    orth (recipe A) = recipe (Fm.neg A) ↔ recipe A = loc A := by
  rw [orth_recipe_eq_iff]
  have hs := recipe_sub_P_sub_loc A
  have hl := P_eq_loc_iff A
  constructor
  · rintro ⟨hA, hnA⟩
    rw [hA]; exact hl.2 hnA
  · intro h
    have hPA : recipe A = P A := le_antisymm hs.1 (by rw [h]; exact hs.2)
    exact ⟨hPA, hl.1 (by rw [← hPA]; exact h)⟩

/-- **The calculus is not a model of negation.** At the core `(2 ⊸ 2) ⊗ (2 ⊸ 2)` there is no
gap, but the orthogonal of its calculus is not the calculus of its dual. -/
theorem not_tight_core : orth (recipe (core 2 2 2 2)) ≠ recipe (Fm.neg (core 2 2 2 2)) := by
  intro h
  have h2 := ((orth_recipe_eq_iff _).1 h).2
  exact (recipe_second_order_ssubset le_rfl le_rfl le_rfl le_rfl).ne h2

/-- Pairing with the indicator of a row is the row sum. -/
theorem row_pairing {n m : ℕ} (f : Fin n × Fin m → ℝ≥0∞) (a : Fin n) :
    ∑ p : Fin n × Fin m, (if p.1 = a then (1 : ℝ≥0∞) else 0) * f p = ∑ b, f (a, b) := by
  rw [Fintype.sum_prod_type]
  simp only [ite_mul, one_mul, zero_mul]
  rw [Finset.sum_eq_single a (fun c _ hc => by simp [hc]) (by simp)]
  simp

/-- **The local calculus at first order is the PCS.** The row indicators are certain states of the
dual, and they cut out the row-substochastic matrices. -/
theorem P_lolli_eq_loc (n m : ℕ) :
    P (lolli (base n) (base m)) = loc (lolli (base n) (base m)) := by
  classical
  refine le_antisymm (recipe_sub_P_sub_loc _).2 fun x hx => ?_
  rw [P_lolli_base]
  refine (ConstructiveProb.PCS.mem_lin_iff (X := Fin n) (Y := Fin m) x).2 fun a => ?_
  let y : Fin n × Fin m → ℝ≥0∞ := fun p => if p.1 = a then 1 else 0
  have hy : y ∈ sharpP (Fm.neg (lolli (base n) (base m))) := by
    refine ⟨?_, fun p => by by_cases h : p.1 = a <;> simp [y, h]⟩
    show y ∈ orth (P (lolli (base n) (base m)))
    rw [P_lolli_base]
    intro t ht
    have hrow := (ConstructiveProb.PCS.mem_lin_iff (X := Fin n) (Y := Fin m) t).1 ht a
    have hp : ConstructiveProb.PCS.pairing t y
        = ∑ p : Fin n × Fin m, (if p.1 = a then (1 : ℝ≥0∞) else 0) * t p :=
      Finset.sum_congr rfl fun p _ => mul_comm _ _
    rw [hp, row_pairing]
    exact hrow
  have h1 : ∑ p : Fin n × Fin m, (if p.1 = a then (1 : ℝ≥0∞) else 0) * x p ≤ 1 := hx y hy
  rwa [row_pairing] at h1

/-- **First-order types are tight.** -/
theorem tight_lolli (n m : ℕ) :
    orth (recipe (lolli (base n) (base m))) = recipe (Fm.neg (lolli (base n) (base m))) :=
  (tight_iff_recipe_eq_loc _).2 ((recipe_lolli_base n m).trans (P_lolli_eq_loc n m))

/-- The core over data types with at least two elements is not tight. -/
theorem not_tight_core' {n m n' m' : ℕ} (hn : 2 ≤ n) (hm : 2 ≤ m) (hn' : 2 ≤ n')
    (hm' : 2 ≤ m') : orth (recipe (core n m n' m')) ≠ recipe (Fm.neg (core n m n' m')) := by
  intro h
  exact (recipe_second_order_ssubset hn hm hn' hm').ne ((orth_recipe_eq_iff _).1 h).2

/-- **Tightness is not preserved by `⊗`.** The first-order types `n ⊸ m` and `n' ⊸ m'` are tight,
and their tensor is not once every data type has at least two elements. -/
theorem tight_not_tensor_closed {n m n' m' : ℕ} (hn : 2 ≤ n) (hm : 2 ≤ m) (hn' : 2 ≤ n')
    (hm' : 2 ≤ m') :
    orth (recipe (lolli (base n) (base m))) = recipe (Fm.neg (lolli (base n) (base m))) ∧
    orth (recipe (lolli (base n') (base m'))) = recipe (Fm.neg (lolli (base n') (base m'))) ∧
    orth (recipe (tens (lolli (base n) (base m)) (lolli (base n') (base m'))))
      ≠ recipe (Fm.neg (tens (lolli (base n) (base m)) (lolli (base n') (base m')))) :=
  ⟨tight_lolli n m, tight_lolli n' m', not_tight_core' hn hm hn' hm'⟩

end ConstructiveProb.Linear

/-! ### Simplices -/

namespace ConstructiveProb

section FiniteFrame

variable {P : Type*} [PartialOrder P] [Fintype P]

/-- **On a finite frame the calculus is a simplex.** Two mixtures of point valuations that agree
on every lower set have the same weights. -/
theorem mix_deltaPoint_inj {w w' : P → ℝ≥0∞} (hw : ∑ p, w p = 1)
    (h : ∀ U : LowerSet P, ∑ q, w q * deltaPoint q U = ∑ q, w' q * deltaPoint q U) :
    w = w' := by
  classical
  funext p
  have key : ∀ u : P → ℝ≥0∞, ∑ q, u q * deltaPoint q (LowerSet.Iic p)
      = ∑ q, u q * deltaPoint q (LowerSet.Iio p) + u p := by
    intro u
    have hpt : ∀ x, (if x ≤ p then u x else 0)
        = (if x < p then u x else 0) + if x = p then u x else 0 := by
      intro x
      by_cases hx : x = p
      · subst hx; simp
      · by_cases hle : x ≤ p
        · simp [hle, lt_of_le_of_ne hle hx, hx]
        · have hlt : ¬ x < p := fun hlt => hle hlt.le
          simp [hle, hx, hlt]
    simp only [deltaPoint, mul_ite, mul_one, mul_zero, LowerSet.mem_Iic_iff, LowerSet.mem_Iio_iff]
    rw [Finset.sum_congr rfl fun x _ => hpt x, Finset.sum_add_distrib, Finset.sum_ite_eq']
    simp
  have hfin : ∑ q, w q * deltaPoint q (LowerSet.Iio p) ≠ ∞ := by
    refine ne_top_of_le_ne_top (b := ∑ q, w q) (by rw [hw]; exact ENNReal.one_ne_top) ?_
    refine Finset.sum_le_sum fun q _ => ?_
    calc w q * deltaPoint q (LowerSet.Iio p) ≤ w q * 1 :=
          mul_le_mul_right ((deltaPoint q).le_one _) _
      _ = w q := mul_one _
  have e1 := key w
  have e2 := key w'
  rw [h, h (LowerSet.Iio p)] at e1
  rw [e2] at e1
  rw [← h (LowerSet.Iio p)] at e1
  exact ((ENNReal.add_right_inj hfin).1 e1).symm

end FiniteFrame

namespace PCS

/-- **At `Bool ⊸ Bool` the calculus is not a simplex.** The even mixture of the identity and
negation and the even mixture of the two constants are the same behaviour. -/
theorem lin_not_simplex :
    ∃ f g h k : Fin 2 → Option (Fin 2), f ≠ h ∧ f ≠ k ∧ g ≠ h ∧ g ≠ k ∧
      (fun ab => 2⁻¹ * det f ab + 2⁻¹ * det g ab)
        = (fun ab => 2⁻¹ * det h ab + 2⁻¹ * det k ab) := by
  refine ⟨fun a => some a, fun a => some (1 - a), fun _ => some 0, fun _ => some 1,
    ?_, ?_, ?_, ?_, ?_⟩
  · intro hf; have := congrFun hf 1; simp at this
  · intro hf; have := congrFun hf 0; simp at this
  · intro hf; have := congrFun hf 0; simp at this
  · intro hf; have := congrFun hf 1; simp at this
  · funext ab
    obtain ⟨a, b⟩ := ab
    fin_cases a <;> fin_cases b <;> simp [det]

end PCS

/-! ### Effect-algebra states -/

section EffectStates

variable {Ω : Type*} [Order.Frame Ω]

/-- States in the sense of effect algebras, with disjointness as orthogonality: normalized,
monotone, and additive on disjoint joins. -/
structure IsPartialSumState (q : Ω → ℝ≥0∞) : Prop where
  bot : q ⊥ = 0
  top : q ⊤ = 1
  mono : Monotone q
  add : ∀ a b, a ⊓ b = ⊥ → q (a ⊔ b) = q a + q b

theorem Valuation.isPartialSumState (v : Valuation Ω) : IsPartialSumState (v : Ω → ℝ≥0∞) :=
  ⟨v.map_bot, v.map_top, v.mono, fun _ _ h => v.additive_of_disjoint h⟩

/-- **Partial-sum states are not the calculus.** On the five-element frame some partial-sum state
violates modularity, an affine law valid on every valuation. -/
theorem partialSum_not_modular :
    ∃ q : LowerSet V → ℝ≥0∞, IsPartialSumState q ∧
      ¬ ∀ a b, q a + q b = q (a ⊔ b) + q (a ⊓ b) :=
  ⟨qV, ⟨qV_bot, qV_top, qV_mono, qV_disjoint_additive⟩, qV_not_modular⟩

/-- **Orthosupplements exist only in Boolean frames.** If every element has a complement, the
pseudocomplement satisfies excluded middle. -/
theorem em_of_complemented (h : ∀ a : Ω, ∃ b, IsCompl a b) (a : Ω) : a ⊔ aᶜ = ⊤ := by
  obtain ⟨b, hb⟩ := h a
  have hle : b ≤ aᶜ := le_compl_iff_disjoint_left.2 hb.disjoint
  exact top_le_iff.1 (hb.sup_eq_top ▸ sup_le_sup_left hle a)

end EffectStates

/-! ### Unique representing measures -/

namespace Cfg

variable {Ev : Type}

/-- The σ-algebra generated by the events. -/
abbrev evSigma (Ev : Type) : MeasurableSpace (Cfg Ev) :=
  MeasurableSpace.generateFrom (Set.range (atom (Ev := Ev)))

theorem evSigma_le : evSigma Ev ≤ (inferInstance : MeasurableSpace (Cfg Ev)) :=
  MeasurableSpace.generateFrom_le fun _ ⟨e, he⟩ => he ▸ atom_mem_measurableSet e

/-- Finite intersections of events. -/
def cyl (Ev : Type) : Set (Set (Cfg Ev)) := {A | ∃ F : Finset Ev, A = ⋂ e ∈ F, atom e}

theorem isPiSystem_cyl : IsPiSystem (cyl Ev) := by
  classical
  rintro _ ⟨F, rfl⟩ _ ⟨G, rfl⟩ -
  refine ⟨F ∪ G, ?_⟩
  ext σ
  simp only [Set.mem_inter_iff, Set.mem_iInter, Finset.mem_union]
  constructor
  · rintro ⟨h1, h2⟩ e (he | he)
    exacts [h1 e he, h2 e he]
  · intro h
    exact ⟨fun e he => h e (Or.inl he), fun e he => h e (Or.inr he)⟩

theorem generateFrom_cyl : MeasurableSpace.generateFrom (cyl Ev) = evSigma Ev := by
  classical
  apply le_antisymm
  · refine MeasurableSpace.generateFrom_le ?_
    rintro _ ⟨F, rfl⟩
    refine Finset.measurableSet_biInter F fun e _ => ?_
    exact MeasurableSpace.measurableSet_generateFrom ⟨e, rfl⟩
  · refine MeasurableSpace.generateFrom_le ?_
    rintro _ ⟨e, rfl⟩
    refine MeasurableSpace.measurableSet_generateFrom ⟨{e}, ?_⟩
    simp

/-- A certain-state presentation with a meet: some event is certain in every certain state, and
for every two events some event is certain exactly when both are. -/
structure HasMeets (S : Set (Ev → ℝ≥0∞)) : Prop where
  top : ∃ t, ∀ s ∈ S, s t = 1
  meet : ∀ a b, ∃ c, ∀ s ∈ S, (s c = 1 ↔ s a = 1 ∧ s b = 1)

theorem HasMeets.finset {S : Set (Ev → ℝ≥0∞)} (hm : HasMeets S) (F : Finset Ev) :
    ∃ c, ∀ s ∈ S, (s c = 1 ↔ ∀ e ∈ F, s e = 1) := by
  classical
  induction F using Finset.induction_on with
  | empty =>
    obtain ⟨t, ht⟩ := hm.top
    exact ⟨t, fun s hs => ⟨fun _ e he => absurd he (Finset.notMem_empty e), fun _ => ht s hs⟩⟩
  | insert a F ha ih =>
    obtain ⟨c, hc⟩ := ih
    obtain ⟨d, hd⟩ := hm.meet a c
    refine ⟨d, fun s hs => ?_⟩
    rw [hd s hs, hc s hs]
    simp only [Finset.mem_insert, forall_eq_or_imp]

/-- Off the bad set of a window containing `F` and `c`, the intersection of `F` is the event `c`. -/
theorem inter_diff_bad [DecidableEq Ev] {S : Set (Ev → ℝ≥0∞)} {F : Finset Ev}
    {c : Ev} (hc : ∀ s ∈ S, (s c = 1 ↔ ∀ e ∈ F, s e = 1)) :
    (⋂ e ∈ F, atom e) \ bad S (insert c F) = atom c \ bad S (insert c F) := by
  ext σ
  simp only [Set.mem_sdiff, Set.mem_iInter, bad, Set.mem_setOf_eq, not_not, atom]
  constructor
  · rintro ⟨h, hg⟩
    refine ⟨?_, hg⟩
    obtain ⟨s, hs, hse⟩ := hg
    have hv : ∀ e ∈ insert c F, s e = vec σ e := fun e he => hse ⟨e, he⟩
    have : s c = 1 := (hc s hs).2 fun e he => by
      rw [hv e (Finset.mem_insert_of_mem he), vec, if_pos (h e he)]
    rw [hv c (Finset.mem_insert_self c F), vec] at this
    by_contra hσ
    rw [if_neg hσ] at this
    exact zero_ne_one this
  · rintro ⟨h, hg⟩
    refine ⟨fun e he => ?_, hg⟩
    obtain ⟨s, hs, hse⟩ := hg
    have hv : ∀ e ∈ insert c F, s e = vec σ e := fun e he => hse ⟨e, he⟩
    have hsc : s c = 1 := by rw [hv c (Finset.mem_insert_self c F), vec, if_pos h]
    have := (hc s hs).1 hsc e he
    rw [hv e (Finset.mem_insert_of_mem he), vec] at this
    by_contra hσ
    rw [if_neg hσ] at this
    exact zero_ne_one this

/-- **Representing measures are unique on the events' σ-algebra.** For a presentation with
meets, two probability measures that vanish on every bad set and give every event the same
mass agree on the σ-algebra generated by the events. -/
theorem trim_eq_of_meet {S : Set (Ev → ℝ≥0∞)} (hm : HasMeets S)
    (μ ν : ProbabilityMeasure (Cfg Ev))
    (hμ : ∀ F, (μ : Measure (Cfg Ev)) (bad S F) = 0) (hν : ∀ F, (ν : Measure (Cfg Ev)) (bad S F) = 0)
    (h : ∀ e, (μ : Measure (Cfg Ev)) (atom e) = (ν : Measure (Cfg Ev)) (atom e)) :
    (μ : Measure (Cfg Ev)).trim evSigma_le = (ν : Measure (Cfg Ev)).trim evSigma_le := by
  classical
  have hcylm : ∀ A ∈ cyl Ev, MeasurableSet[evSigma Ev] A := fun A hA => by
    rw [← generateFrom_cyl]; exact MeasurableSpace.measurableSet_generateFrom hA
  refine ext_of_generate_finite (m0 := evSigma Ev) (cyl Ev) generateFrom_cyl.symm isPiSystem_cyl
    ?_ ?_
  · rintro _ ⟨F, rfl⟩
    rw [trim_measurableSet_eq _ (hcylm _ ⟨F, rfl⟩), trim_measurableSet_eq _ (hcylm _ ⟨F, rfl⟩)]
    obtain ⟨c, hc⟩ := hm.finset F
    have key : ∀ ρ : Measure (Cfg Ev), ρ (bad S (insert c F)) = 0 →
        ρ (⋂ e ∈ F, atom e) = ρ (atom c) := fun ρ hρ => by
      rw [← measure_sdiff_null hρ, inter_diff_bad hc, measure_sdiff_null hρ]
    rw [key _ (hμ _), key _ (hν _), h c]
  · rw [trim_measurableSet_eq _ MeasurableSet.univ, trim_measurableSet_eq _ MeasurableSet.univ,
      measure_univ, measure_univ]

/-- The sharp valuations of a frame, as vectors. -/
def sharpVecs (Ω : Type) [Order.Frame Ω] : Set (Ω → ℝ≥0∞) :=
  {x | ∃ v : Valuation Ω, v.IsSharp ∧ x = v}

/-- **The certain states of a frame have meets.** -/
theorem hasMeets_sharpVecs (Ω : Type) [Order.Frame Ω] : HasMeets (sharpVecs Ω) := by
  refine ⟨⟨⊤, ?_⟩, fun a b => ⟨a ⊓ b, ?_⟩⟩
  · rintro _ ⟨v, -, rfl⟩; exact v.map_top
  · rintro _ ⟨v, hv, rfl⟩
    constructor
    · intro h
      exact ⟨le_antisymm (v.le_one a) (h ▸ v.mono inf_le_left),
        le_antisymm (v.le_one b) (h ▸ v.mono inf_le_right)⟩
    · rintro ⟨ha, hb⟩
      rcases hv (a ⊓ b) with h0 | h1
      · have hm := v.modular a b
        rw [ha, hb, h0, add_zero] at hm
        have : (1 : ℝ≥0∞) + 1 ≤ 1 := hm ▸ v.le_one _
        norm_num at this
      · exact h1

/-- **Valuations on a frame have at most one representing measure** on the σ-algebra generated
by the events. -/
theorem frame_rep_unique {Ω : Type} [Order.Frame Ω] (μ ν : ProbabilityMeasure (Cfg Ω))
    (hμ : ∀ F, (μ : Measure (Cfg Ω)) (bad (sharpVecs Ω) F) = 0)
    (hν : ∀ F, (ν : Measure (Cfg Ω)) (bad (sharpVecs Ω) F) = 0)
    (h : ∀ e, (μ : Measure (Cfg Ω)) (atom e) = (ν : Measure (Cfg Ω)) (atom e)) :
    (μ : Measure (Cfg Ω)).trim evSigma_le = (ν : Measure (Cfg Ω)).trim evSigma_le :=
  trim_eq_of_meet (hasMeets_sharpVecs Ω) μ ν hμ hν h

end Cfg

/-! ### The closed calculus as a limit of finite calculi -/

section Limit

open CategoryTheory

variable {E : Type}

theorem restr_mem_Mix {S : Set (E → ℝ≥0∞)} {F G : Finset E} (hGF : G ≤ F)
    {y : F → ℝ≥0∞} (hy : y ∈ Mix (restr F '' S)) :
    (fun e : G => y ⟨e.1, hGF e.2⟩) ∈ Mix (restr G '' S) := by
  obtain ⟨n, w, s, hs, hw, rfl⟩ := hy
  choose t ht hts using hs
  refine ⟨n, w, fun i => restr G (t i), fun i => ⟨t i, ht i, rfl⟩, hw, ?_⟩
  funext e
  simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, ← hts]
  rfl

/-- The calculus on a finite window. -/
abbrev WinObj (S : Set (E → ℝ≥0∞)) (F : Finset E) : Type :=
  {y : F → ℝ≥0∞ // y ∈ Mix (restr F '' S)}

/-- Restriction from a window to a smaller one. -/
def winRestr (S : Set (E → ℝ≥0∞)) {F G : Finset E} (h : G ≤ F) (y : WinObj S F) : WinObj S G :=
  ⟨fun e => y.1 ⟨e.1, h e.2⟩, restr_mem_Mix h y.2⟩

/-- The calculi on finite windows, with restriction maps. -/
def windowCalc (S : Set (E → ℝ≥0∞)) : (Finset E)ᵒᵖ ⥤ Type where
  obj F := WinObj S F.unop
  map f := TypeCat.ofHom (winRestr S (leOfHom f.unop))
  map_id _ := rfl
  map_comp _ _ := rfl

/-- The closed calculus: the functions satisfying every finite law valid on the certain
states. -/
def closedCalc (S : Set (E → ℝ≥0∞)) : Type :=
  {x : E → ℝ≥0∞ // ∀ L : FinLaw E, (∀ s ∈ S, L.Holds s) → L.Holds x}

/-- The component of a section at a window. -/
def secAt {S : Set (E → ℝ≥0∞)} (u : (windowCalc S).sections) (F : Finset E) : WinObj S F :=
  u.1 (Opposite.op F)

theorem secAt_restr {S : Set (E → ℝ≥0∞)} (u : (windowCalc S).sections) {F G : Finset E}
    (h : G ≤ F) : winRestr S h (secAt u F) = secAt u G :=
  u.2 (homOfLE h).op

/-- **The closed calculus is the set of compatible families of finite calculi.** -/
noncomputable def closedCalcEquivSections {S : Set (E → ℝ≥0∞)} (hS : ∀ s ∈ S, IsSharpVec s) :
    closedCalc S ≃ (windowCalc S).sections where
  toFun x := ⟨fun F => (⟨restr F.unop x.1, (laws_iff_local_Mix hS x.1).1 x.2 F.unop⟩ :
    WinObj S F.unop), fun _ => rfl⟩
  invFun u := ⟨fun e => (secAt u {e}).1 ⟨e, Finset.mem_singleton_self e⟩, by
    rw [laws_iff_local_Mix hS]
    intro F
    have hF : restr F (fun e => (secAt u {e}).1 ⟨e, Finset.mem_singleton_self e⟩)
        = (secAt u F).1 := by
      funext e
      have hle : ({e.1} : Finset E) ≤ F := Finset.singleton_subset_iff.2 e.2
      have := congrArg (fun y : WinObj S {e.1} => y.1 ⟨e.1, Finset.mem_singleton_self _⟩)
        (secAt_restr u hle)
      exact this.symm
    rw [hF]; exact (secAt u F).2⟩
  left_inv x := rfl
  right_inv u := by
    apply Subtype.ext
    funext F
    apply Subtype.ext
    funext e
    have hle : ({e.1} : Finset E) ≤ F.unop := Finset.singleton_subset_iff.2 e.2
    have := congrArg (fun y : WinObj S {e.1} => y.1 ⟨e.1, Finset.mem_singleton_self _⟩)
      (secAt_restr u hle)
    exact this.symm

/-- **The closed calculus is the limit of the calculi on finite windows.** -/
noncomputable def closedCalcEquivLimit {S : Set (E → ℝ≥0∞)} (hS : ∀ s ∈ S, IsSharpVec s) :
    closedCalc S ≃ Limits.limit (windowCalc S) :=
  (closedCalcEquivSections hS).trans (Limits.Types.limitEquivSections (windowCalc S)).symm

end Limit

end ConstructiveProb
