/-
# The valuation monoid and the category of valued frames

* `Val : Frmᵒᵖ ⥤ Type` sends a frame to its valuations and a frame homomorphism to pullback;
  `SpVal` is its category of elements: objects are pairs `(P, v)`, morphisms are frame
  homomorphisms `φ` with `w ∘ φ = v`.
* `V P` is the free commutative monoid on a lattice `P` modulo `[a] + [b] = [a ⊔ b] + [a ⊓ b]` and
  `[⊥] = 0`. Additive maps out of `V P` are exactly the modular maps out of `P` that vanish at `⊥`
  (`VMonoid.lift`, `VMonoid.lift_ι`, `VMonoid.hom_ext`). So the lattice valuations on `P` are the
  monoid homomorphisms `V P →+ ℝ≥0∞` sending `[⊤]` to `1` whose composite with `ι` is monotone
  (`VMonoid.lvaluation_equiv`).
* **Flags** (`VMonoid.exists_flag`): in every lattice with a bottom element, every element of `V P`
  is `[α₁] + ⋯ + [αₙ]` for a chain `α₁ ≤ ⋯ ≤ αₙ`. Distributivity is not needed.
-/
import ConstructiveProb.Points
import ConstructiveProb.GeneralValuation
import ConstructiveProb.NonDistributive
import Mathlib.Order.Category.Frm
import Mathlib.CategoryTheory.Elements

open scoped ENNReal
open CategoryTheory

namespace ConstructiveProb

/-! ### The valuation functor and its category of elements -/

/-- **The valuation functor** `Frmᵒᵖ ⥤ Type`: valuations, pulled back along frame homomorphisms. -/
noncomputable def ValF : Frmᵒᵖ ⥤ Type _ where
  obj P := Valuation P.unop
  map {P Q} φ := TypeCat.ofHom fun v : Valuation P.unop => (v.comap φ.unop.hom : Valuation Q.unop)
  map_id P := by
    apply TypeCat.Hom.ext; apply TypeCat.Fun.ext; funext v; exact Valuation.comap_id v
  map_comp φ ψ := by
    apply TypeCat.Hom.ext; apply TypeCat.Fun.ext; funext v; exact Valuation.comap_comp _ _ v

/-- **Valued frames**: the category of elements of `ValF`. An object is a frame with a valuation;
a morphism `(Q, w) ⟶ (P, v)` is a frame homomorphism `φ : P → Q` with `w ∘ φ = v`. -/
abbrev SpVal := ValF.Elements

theorem SpVal.hom_spec {x y : SpVal} (f : x ⟶ y) : ValF.map f.1 x.2 = y.2 := f.2

/-! ### The valuation monoid -/

namespace VMonoid

variable (P : Type*) [Lattice P] [OrderBot P]

/-- The generating relation: modularity and `[⊥] = 0`. -/
inductive Gen : Multiset P → Multiset P → Prop
  | modular (a b : P) : Gen ({a} + {b}) ({a ⊔ b} + {a ⊓ b})
  | bot : Gen {⊥} 0

/-- The congruence generated by `Gen`. -/
def con : AddCon (Multiset P) := addConGen (Gen P)

/-- **The valuation monoid** `V P`. -/
abbrev V := (con P).Quotient

variable {P}

/-- The class `[a]`. -/
def ι (a : P) : V P := (con P).mk' {a}

theorem ι_modular (a b : P) : ι a + ι b = ι (a ⊔ b) + ι (a ⊓ b) := by
  simp only [ι, ← map_add]
  exact (con P).eq.2 (AddConGen.Rel.of _ _ (Gen.modular a b))

theorem ι_bot : ι (⊥ : P) = 0 := by
  simp only [ι]
  rw [← map_zero (con P).mk']
  exact (con P).eq.2 (AddConGen.Rel.of _ _ Gen.bot)

theorem mk_eq_sum (s : Multiset P) : (con P).mk' s = (s.map ι).sum := by
  induction s using Multiset.induction_on with
  | empty => simp
  | cons a s ih =>
    rw [Multiset.map_cons, Multiset.sum_cons, ← ih, ← Multiset.singleton_add, map_add]; rfl

variable {M : Type*} [AddCommMonoid M]

/-- A modular map vanishing at `⊥`. -/
structure Modular (f : P → M) : Prop where
  bot : f ⊥ = 0
  modular : ∀ a b, f a + f b = f (a ⊔ b) + f (a ⊓ b)

/-- **Universal property, existence.** -/
def lift (f : P → M) (hf : Modular f) : V P →+ M :=
  (con P).lift ((Multiset.sumAddMonoidHom).comp (Multiset.mapAddMonoidHom f)) (by
    refine AddCon.addConGen_le.2 fun x y h => ?_
    rw [AddCon.ker_rel]
    cases h with
    | modular a b => simp [hf.modular a b]
    | bot => simp [hf.bot])

theorem lift_ι (f : P → M) (hf : Modular f) (a : P) : lift f hf (ι a) = f a := by
  simp [lift, ι]

/-- **Universal property, uniqueness.** -/
theorem hom_ext {h h' : V P →+ M} (H : ∀ a, h (ι a) = h' (ι a)) : h = h' := by
  apply AddMonoidHom.ext
  intro x
  refine AddCon.induction_on x fun s => ?_
  · change h ((con P).mk' s) = h' ((con P).mk' s)
    rw [mk_eq_sum, map_multiset_sum, map_multiset_sum, Multiset.map_map, Multiset.map_map]
    congr 1
    exact Multiset.map_congr rfl fun a _ => H a

/-- Every additive map out of `V P` restricts to a modular map vanishing at `⊥`. -/
theorem modular_of_hom (h : V P →+ M) : Modular (fun a => h (ι a)) :=
  ⟨by rw [ι_bot, map_zero], fun a b => by rw [← map_add, ← map_add, ι_modular]⟩

/-- **Valuations are monoid homomorphisms.** On a bounded lattice, lattice valuations correspond
to additive maps `V P → [0,∞]` that send `[⊤]` to `1` and are monotone on generators. -/
noncomputable def lvaluation_equiv {P : Type*} [Lattice P] [BoundedOrder P] :
    LValuation P ≃
      {h : V P →+ ℝ≥0∞ // h (ι ⊤) = 1 ∧ Monotone fun a => h (ι a)} where
  toFun v := ⟨lift v ⟨v.map_bot, v.modular⟩, by rw [lift_ι]; exact v.map_top,
    fun a b hab => by simp only [lift_ι]; exact v.mono hab⟩
  invFun h := ⟨fun a => h.1 (ι a), (modular_of_hom h.1).bot, h.2.1, h.2.2,
    (modular_of_hom h.1).modular⟩
  left_inv v := by
    cases v; simp only [lift_ι]
  right_inv h := by
    apply Subtype.ext
    exact hom_ext fun a => by simp only [lift_ι]

/-! ### Flags -/

/-- Inserting `y` into a chain: the result is a chain whose sum is `[y]` plus the sum of the
chain, and every common lower bound of `y` and the chain lies below all of it. -/
theorem insert_chain (y : P) : ∀ cs : List P, cs.Pairwise (· ≤ ·) →
    ∃ l : List P, l.Pairwise (· ≤ ·) ∧
      (∀ w, w ≤ y → (∀ c ∈ cs, w ≤ c) → ∀ z ∈ l, w ≤ z) ∧
      ι y + (cs.map ι).sum = (l.map ι).sum
  | [], _ => ⟨[y], List.pairwise_singleton _ y, fun w hw _ z hz => by
      rw [List.mem_singleton.1 hz]; exact hw, by simp⟩
  | c :: cs, hs => by
    obtain ⟨hc, hs'⟩ := List.pairwise_cons.1 hs
    obtain ⟨l, hl, hlow, hsum⟩ := insert_chain (y ⊔ c) cs hs'
    refine ⟨(y ⊓ c) :: l, List.pairwise_cons.2 ⟨fun z hz => hlow _ (le_trans inf_le_left le_sup_left)
      (fun c' hc' => le_trans inf_le_right (hc c' hc')) z hz, hl⟩, fun w hw hwc z hz => ?_, ?_⟩
    · rcases List.mem_cons.1 hz with rfl | hz
      · exact le_inf hw (hwc c (List.mem_cons_self ..))
      · exact hlow w (le_trans hw le_sup_left) (fun c' hc' => hwc c' (List.mem_cons_of_mem _ hc'))
          z hz
    · rw [List.map_cons, List.sum_cons, ← add_assoc, ι_modular, List.map_cons, List.sum_cons,
        add_comm (ι (y ⊔ c)), add_assoc, hsum]

/-- **Flag normal form.** Every element of `V P` is the sum over a chain. -/
theorem exists_flag (x : V P) : ∃ l : List P, l.Pairwise (· ≤ ·) ∧ x = (l.map ι).sum := by
  refine AddCon.induction_on x fun s => ?_
  · change ∃ l : List P, l.Pairwise (· ≤ ·) ∧ (con P).mk' s = (l.map ι).sum
    rw [mk_eq_sum]
    induction s using Multiset.induction_on with
    | empty => exact ⟨[], List.Pairwise.nil, by simp⟩
    | cons a s ih =>
      obtain ⟨l, hl, hs⟩ := ih
      obtain ⟨l', hl', -, hsum⟩ := insert_chain a l hl
      exact ⟨l', hl', by rw [Multiset.map_cons, Multiset.sum_cons, hs, hsum]⟩

/-! ### Failure at `M3` -/

theorem M3_atoms (x y : M3) (hx : x = .a ∨ x = .b ∨ x = .c) (hy : y = .a ∨ y = .b ∨ y = .c)
    (hxy : x ≠ y) : ι x + ι y = ι M3.o := by
  rw [ι_modular]
  have h1 : x ⊔ y = M3.o := by
    rcases hx with rfl | rfl | rfl <;> rcases hy with rfl | rfl | rfl <;>
      first | exact absurd rfl hxy | rfl
  have h2 : x ⊓ y = ⊥ := by
    rcases hx with rfl | rfl | rfl <;> rcases hy with rfl | rfl | rfl <;>
      first | exact absurd rfl hxy | rfl
  rw [h1, h2, ι_bot, add_zero]

/-- **Flags are not unique in `M3`.** `[a] + [⊤] = [c] + [⊤]`. -/
theorem M3_flag_not_unique : ι M3.a + ι M3.o = ι M3.c + ι M3.o :=
  calc ι M3.a + ι M3.o = ι M3.a + (ι M3.b + ι M3.c) := by
        rw [M3_atoms M3.b M3.c (by simp) (by simp) (by decide)]
    _ = (ι M3.a + ι M3.b) + ι M3.c := (add_assoc _ _ _).symm
    _ = ι M3.c + ι M3.o := by
        rw [M3_atoms M3.a M3.b (by simp) (by simp) (by decide), add_comm]

/-- A modular map on `M3` into `[0, ∞]` separating the atoms `b` and `c`. -/
def m3sep : M3 → ℝ≥0∞
  | .z => 0
  | .c => 0
  | _ => ⊤

theorem m3sep_modular : Modular m3sep := by
  refine ⟨rfl, fun x y => ?_⟩
  have hs : x ⊔ y = M3.sup x y := rfl
  have hi : x ⊓ y = M3.inf x y := rfl
  rw [hs, hi]
  cases x <;> cases y <;> simp [m3sep, M3.sup, M3.inf]

/-- **`V M3` is not cancellative.** `[a] + [b] = [a] + [c]` but `[b] ≠ [c]`. -/
theorem M3_not_cancel : ι M3.a + ι M3.b = ι M3.a + ι M3.c ∧ ι M3.b ≠ ι M3.c := by
  refine ⟨by rw [M3_atoms M3.a M3.b (by simp) (by simp) (by decide),
    M3_atoms M3.a M3.c (by simp) (by simp) (by decide)], fun h => ?_⟩
  have := congrArg (lift m3sep m3sep_modular) h
  rw [lift_ι, lift_ι] at this
  exact ENNReal.top_ne_zero this

end VMonoid

end ConstructiveProb
