/-
# Slack does not determine the valuation

`Basic.lean` proves slack is *submodular* (`Valuation.slack_submodular`): a necessary
condition every valuation's slack function must satisfy. The converse direction — that
fixing a submodular slack function pins down a unique valuation with that slack — is
false, even under the full strength of modularity. This file exhibits the counterexample.

**The space.** `ThreePt = {ptA, ptB, ptZ}`, topologized so `{ptA}` and `{ptB}` are open
but `ptZ` has no open neighbourhood except the whole space: every open set either omits
`ptZ` or is everything. So `ptZ` is a "silent" point, undetectable by any proper open —
the same phenomenon as the Sierpiński space's unrefutable `halts`, one level more subtle.

**The counterexample.** For weights `a, b, c ≥ 0` with `a + b + c = 1`, the point measure
`a·δ(ptA) + b·δ(ptB) + c·δ(ptZ)`, read through the GMT bridge
(`Measure.toValuationOpens`), gives a valuation on `Opens ThreePt`. Its slack, by
`toValuationOpens_slack_eq_frontier`, is the measure of a frontier, and every open set's
frontier is either `∅` or `{ptZ}` (`frontier_subset_ptZ` below) — a fact about the
*topology* alone, independent of the measure. So the slack function depends only on `c`,
the mass of the silent point: any two choices of `a, b` with `a + b` fixed give *the same
slack function* while producing different valuations (`v {ptA} = a` differs).
Modularity, submodularity, monotonicity — everything the earlier theorem could ask of a
valuation — is satisfied by both, and slack alone cannot tell them apart.
-/
import ConstructiveProb.Basic
import Mathlib.MeasureTheory.Measure.Dirac

open scoped ENNReal
open TopologicalSpace MeasureTheory

namespace ConstructiveProb

/-! ### A three-point space with one unseparated point -/

/-- Three points: two separated by opens, one — `ptZ` — silent. -/
inductive ThreePt : Type
  | ptA : ThreePt
  | ptB : ThreePt
  | ptZ : ThreePt
deriving DecidableEq, Fintype

open ThreePt

/-- The topology generated by the two singletons `{ptA}`, `{ptB}`: its opens are
exactly `∅, {ptA}, {ptB}, {ptA, ptB}`, and the whole space — nothing properly between
`{ptA, ptB}` and `univ` ever appears, so `ptZ` has no open neighbourhood but `univ`
itself. -/
instance : TopologicalSpace ThreePt :=
  TopologicalSpace.generateFrom {{ptA}, {ptB}}

theorem isOpen_ptA : IsOpen ({ptA} : Set ThreePt) :=
  TopologicalSpace.isOpen_generateFrom_of_mem (by simp)

theorem isOpen_ptB : IsOpen ({ptB} : Set ThreePt) :=
  TopologicalSpace.isOpen_generateFrom_of_mem (by simp)

instance : MeasurableSpace ThreePt := ⊤

instance : OpensMeasurableSpace ThreePt := ⟨le_top⟩

instance : MeasurableSingletonClass ThreePt := ⟨fun _ => trivial⟩

/-! ### The key topological fact: every open's frontier hides inside `{ptZ}` -/

/-- For *any* set `U`, the part of its complement missing `ptZ` is open: it is a
subset of the discrete two-point set `{ptA, ptB}`, and every subset of `{ptA, ptB}`
is open here. -/
theorem isOpen_compl_diff_ptZ (U : Set ThreePt) : IsOpen (Uᶜ \ {ptZ}) := by
  by_cases hA : ptA ∈ U <;> by_cases hB : ptB ∈ U
  · have : Uᶜ \ {ptZ} = (∅ : Set ThreePt) := by
      ext x; cases x <;> simp_all
    rw [this]; exact isOpen_empty
  · have : Uᶜ \ {ptZ} = ({ptB} : Set ThreePt) := by
      ext x; cases x <;> simp_all
    rw [this]; exact isOpen_ptB
  · have : Uᶜ \ {ptZ} = ({ptA} : Set ThreePt) := by
      ext x; cases x <;> simp_all
    rw [this]; exact isOpen_ptA
  · have : Uᶜ \ {ptZ} = ({ptA, ptB} : Set ThreePt) := by
      ext x; cases x <;> simp_all
    rw [this]; exact isOpen_ptA.union isOpen_ptB

/-- **The frontier of every open set lies in `{ptZ}`.** A purely topological fact,
independent of any measure: the only place excluded middle can fail for an open set of
`ThreePt` is at the silent point. -/
theorem frontier_subset_ptZ {U : Set ThreePt} (hU : IsOpen U) : frontier U ⊆ {ptZ} := by
  rw [hU.frontier_eq]
  intro x hx
  by_contra hxz
  simp only [Set.mem_singleton_iff] at hxz
  have hxU : x ∉ U := fun h => hx.2 h
  have hmem : x ∈ Uᶜ \ {ptZ} := ⟨hxU, hxz⟩
  have hsub : Uᶜ \ {ptZ} ⊆ interior Uᶜ :=
    interior_maximal Set.sdiff_subset (isOpen_compl_diff_ptZ U)
  have : x ∈ interior Uᶜ := hsub hmem
  rw [interior_compl] at this
  exact this hx.1

/-! ### The measure family: weight `a` at `ptA`, `b` at `ptB`, `c` at `ptZ` -/

/-- `pointMeasure a b c` puts mass `a, b, c` at `ptA, ptB, ptZ`. -/
noncomputable def pointMeasure (a b c : ℝ≥0∞) : Measure ThreePt :=
  a • Measure.dirac ptA + b • Measure.dirac ptB + c • Measure.dirac ptZ

theorem pointMeasure_apply (a b c : ℝ≥0∞) (s : Set ThreePt) :
    pointMeasure a b c s
      = a * s.indicator 1 ptA + b * s.indicator 1 ptB + c * s.indicator 1 ptZ := by
  simp [pointMeasure, Measure.add_apply, Measure.smul_apply, smul_eq_mul]

theorem pointMeasure_isProbability {a b c : ℝ≥0∞} (h : a + b + c = 1) :
    IsProbabilityMeasure (pointMeasure a b c) := by
  constructor
  rw [pointMeasure_apply]
  simp [h]

theorem pointMeasure_singleton_ptA (a b c : ℝ≥0∞) : pointMeasure a b c {ptA} = a := by
  rw [pointMeasure_apply]; simp

theorem pointMeasure_singleton_ptB (a b c : ℝ≥0∞) : pointMeasure a b c {ptB} = b := by
  rw [pointMeasure_apply]; simp

theorem pointMeasure_singleton_ptZ (a b c : ℝ≥0∞) : pointMeasure a b c {ptZ} = c := by
  rw [pointMeasure_apply]; simp

/-! ### Two valuations, one slack function -/

/-- The open `{ptA}`, as an element of the frame. -/
def openA : Opens ThreePt := ⟨{ptA}, isOpen_ptA⟩

@[simp] theorem coe_openA : (openA : Set ThreePt) = {ptA} := rfl

/-- Two valuations built from measures agreeing off the silent point (same `c`, so the
same total mass `a + b = a' + b'` split differently between `ptA` and `ptB`) have
identical slack, because every open's frontier depends only on the mass at `ptZ`. -/
theorem slack_eq_of_same_ptZ_mass {a b a' b' c : ℝ≥0∞}
    (h : a + b + c = 1) (h' : a' + b' + c = 1) :
    letI := pointMeasure_isProbability h
    letI := pointMeasure_isProbability h'
    (pointMeasure a b c).toValuationOpens.slack
      = (pointMeasure a' b' c).toValuationOpens.slack := by
  letI := pointMeasure_isProbability h
  letI := pointMeasure_isProbability h'
  funext U
  rw [toValuationOpens_slack_eq_frontier, toValuationOpens_slack_eq_frontier]
  rcases Set.subset_singleton_iff_eq.mp (frontier_subset_ptZ U.isOpen) with he | he
  · rw [he]; simp
  · rw [he, pointMeasure_singleton_ptZ, pointMeasure_singleton_ptZ]

/-- **Slack does not determine the valuation.** Two genuinely different valuations —
built from two honest probability measures on a three-point space — share the same
slack function. Submodularity (`Valuation.slack_submodular`) is a real constraint
slack must satisfy, but it, and every other constraint coming from `v`'s own
modularity, is not enough to recover `v` from `slack` alone. -/
theorem exists_ne_valuation_same_slack :
    ∃ v v' : Valuation (Opens ThreePt), v.slack = v'.slack ∧ v ≠ v' := by
  have h1 : (1 / 4 : ℝ≥0∞) + 1 / 4 + 1 / 2 = 1 := by
    have : (1 / 4 : ℝ≥0∞) + 1 / 4 = 1 / 2 := by
      rw [ENNReal.div_add_div_same,
        ENNReal.div_eq_div_iff (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
      norm_num
    rw [this, ENNReal.add_halves]
  have h2 : (1 / 8 : ℝ≥0∞) + 3 / 8 + 1 / 2 = 1 := by
    have : (1 / 8 : ℝ≥0∞) + 3 / 8 = 1 / 2 := by
      rw [ENNReal.div_add_div_same,
        ENNReal.div_eq_div_iff (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
      norm_num
    rw [this, ENNReal.add_halves]
  letI := pointMeasure_isProbability h1
  letI := pointMeasure_isProbability h2
  refine ⟨(pointMeasure (1/4) (1/4) (1/2)).toValuationOpens,
    (pointMeasure (1/8) (3/8) (1/2)).toValuationOpens,
    slack_eq_of_same_ptZ_mass h1 h2, fun hv => ?_⟩
  have hval : (pointMeasure (1/4) (1/4) (1/2)).toValuationOpens openA
      = (pointMeasure (1/8) (3/8) (1/2)).toValuationOpens openA := by rw [hv]
  rw [Measure.toValuationOpens_apply, Measure.toValuationOpens_apply, coe_openA,
    pointMeasure_singleton_ptA, pointMeasure_singleton_ptA] at hval
  norm_num at hval

end ConstructiveProb
